package com.ultimakingdoms.interaction;

import com.ultimakingdoms.civic.*;
import com.ultimakingdoms.api.factions.organization.*;
import com.ultimakingdoms.api.progression.*;
import java.util.*;
import static com.ultimakingdoms.interaction.ActionRegistry.*;

public final class CivicTasks {
    private static CivicService civic(Context c){return CivicRuntime.get(c.server());}
    private static void task(String id,String title,boolean change,List<Field> fields,Handler handler){add(new Task("civic."+id,"Guilds and service",title,"Membership, service qualification, nearby contact and legal access are checked separately. A missing requirement is explained by the service.",false,change,fields,c->civic(c).revision()+":"+OrganizationApi.get(c.server()).revision(),handler));}
    public static void init(){
        targets("chapter",c->{var out=new ArrayList<Choice>();for(int offset=0;offset<=4096;offset+=16){var page=civic(c).knownChapters(c.player,offset);for(var v:page)out.add(new Choice(v.id().toString(),"Chapter at "+v.settlementName(),words(v.status().name()),Map.of("revision",""+civic(c).revision(),"organization",v.organization())));if(page.size()<16)break;}return out;});
        targets("contact",c->{var out=new ArrayList<Choice>();for(int offset=0;offset<=16384;offset+=64){var page=civic(c).dismissibleContacts(c.player,offset,64);for(var v:page)out.add(new Choice(v.npc().toString(),v.label(),v.detail(),Map.of("revision",""+v.revision())));if(page.size()<64)break;}return out;});
        targets("own_membership",c->OrganizationApi.get(c.server()).ownSnapshot(c.player).memberships().stream().filter(m->m.status()==OrganizationMembershipSnapshot.Status.ACTIVE).map(m->new Choice(m.organizationId().toString(),OrganizationApi.get(c.server()).definition(m.organizationId()).map(d->PlayerWords.text(d.nameKey())).orElse(words(m.organizationId().getPath())),"Your active membership",Map.of("revision",""+m.revision()))).toList());
        targets("guild_permission",c->OrganizationApi.get(c.server()).definition(c.id("organization")).stream().flatMap(d->d.services().stream()).map(s->new Choice(s.permission().toString(),words(s.permission().getPath()),"Member: "+s.minimumStanding()+" standing, "+s.requiredDeeds()+" deeds. Independent: "+s.neutralMinimumStanding()+" standing, "+s.neutralRequiredDeeds()+" deeds.")).toList());
        task("status","Read your guild progress",false,List.of(),c->OrganizationApi.get(c.server()).ownSnapshot(c.player).memberships().stream().map(m->c.choices("organization").stream().filter(o->o.value().equals(m.organizationId().toString())).map(Choice::label).findFirst().orElse("Organization")+"\n"+words(m.status().name())+" · standing "+m.standing()+" · verified deeds "+m.deedCount()+" · rank "+m.rank().map(r->words(r.getPath())).orElse("None")).toList());
        for(boolean joining:new boolean[]{true,false})task(joining?"join":"leave",joining?"Join a guild":"Leave a guild",true,List.of(pick("organization","Organization",joining?"organization":"own_membership")),c->{var s=OrganizationApi.get(c.server());var result=joining?s.join(c.player,c.id("organization")):s.leave(c.player,c.id("organization"));if(!result.applied())throw new IllegalArgumentException(PlayerWords.text(result.reason()));return PlayerWords.text(result.reason());});
        task("explain","Check service requirements",false,List.of(pick("organization","Organization","organization"),pick("permission","Service","guild_permission")),c->{var r=OrganizationApi.get(c.server()).explainOwn(c.player,c.id("organization"),c.id("permission"));return words(r.decision().name())+"\n"+String.join("\n",r.reasons().stream().map(PlayerWords::text).toList());});
        for(String action:List.of("introduction","commissions","hospitality","workshop"))task(action,switch(action){case "introduction"->"Find another chapter";case "commissions"->"Browse commissions";case "hospitality"->"Request hospitality access";default->"Browse paid workshop jobs";},true,List.of(pick("organization","Organization","organization")),c->{var s=civic(c);var npc=s.nearbyContact(c.player,c.id("organization")).orElseThrow(()->new IllegalArgumentException("Visit an eligible nearby chapter contact first."));return result(c,switch(action){case "introduction"->s.introduction(c.player,npc);case "commissions"->s.commissions(c.player,npc);case "hospitality"->s.hospitality(c.player,npc);default->s.workshop(c.player,npc);});});
        task("chapters","Browse known chapters",false,List.of(pick("chapter","Chapter","chapter")),c->c.choice("chapter").label()+"\n"+c.choice("chapter").detail());
        task("institutions","Browse known institutions",false,List.of(pick("institution","Institution","institution")),c->c.choice("institution").label()+"\n"+c.choice("institution").detail());
        task("charter","Establish a guild chapter",true,List.of(pick("organization","Organization","organization"),pick("institution","Recognized institution","institution")),c->result(c,civic(c).charter(c.player,c.id("organization"),c.uuid("institution"))));
        task("appoint","Appoint a chapter contact",true,List.of(pick("chapter","Chapter","chapter"),pick("npc","Nearby resident","npc")),c->result(c,civic(c).appoint(c.player,c.uuid("chapter"),BasicTargets.entity(c,"npc"))));
        task("dismiss","Dismiss a chapter contact",true,List.of(pick("contact","Chapter contact","contact")),c->result(c,civic(c).dismiss(c.player,c.uuid("contact"))));
        task("qualify","Check a personal qualification",false,List.of(pick("kind","Qualification",c->enums(ProgressionPredicate.Kind.values())),text("subject","Skill, deity, race or lore entry name"),number("minimum","Minimum level or amount",1)),c->{int minimum=c.integer("minimum");if(minimum<0||minimum>1_000_000)throw new IllegalArgumentException("Minimum must be 0 to 1,000,000.");var answer=ProgressionApi.evaluate(c.player,new ProgressionPredicate(ProgressionPredicate.Kind.valueOf(c.text("kind").toUpperCase(Locale.ROOT)),c.text("subject"),minimum));return (answer.matches()?"Qualified":"Not qualified")+"\n"+PlayerWords.text(answer.reason());});
    }
    private static String result(Context c,CivicService.Result result){if(!result.success())throw new IllegalArgumentException(PlayerWords.text(result.reason()));return PlayerWords.text(result.reason())+result.settlement().map(id->"\nDestination: "+BasicTargets.settlement(c,id)).orElse("");}
    private CivicTasks(){}
}
