package com.ultimakingdoms.interaction;

import com.ultimakingdoms.api.*;
import com.ultimakingdoms.api.factions.*;
import com.ultimakingdoms.factions.*;
import net.minecraft.resources.ResourceLocation;
import java.util.*;
import static com.ultimakingdoms.interaction.ActionRegistry.*;

public final class StandingTasks {
    private static UltimaFactionsService service(Context c){return UltimaFactionsApi.get(c.server());}
    private static void task(String id,String title,boolean change,List<Field> fields,Handler handler){add(new Task("standing."+id,"Administration",title,"Operator maintenance for kingdom reputation. Review the selected player and affected kingdom.",true,change,fields,c->Long.toString(service(c).revision()),handler));}
    public static void init(){
        targets("standing_event",c->{if(!(service(c) instanceof FactionServiceImpl impl))return List.of();return impl.pendingMappings(c.player).stream().map(v->{String name="Player";try{name=BasicTargets.player(c,UUID.fromString(v.payload().get("player")));}catch(Exception ignored){}return new Choice(v.id().toString(),"Standing event "+v.sequence()+" · "+name,"Unmapped change: "+v.payload().getOrDefault("projectedDelta","unknown"),Map.of("revision",""+service(c).revision()));}).toList();});
        targets("mca_community",c->com.ultimakingdoms.compat.mca.McaCompat.operatorCommunities(c.player).stream().map(v->new Choice(v.reference().format(),v.label(),"Native community in "+v.reference().dimension())).toList());
        task("diagnostics","Inspect reputation synchronization",false,List.of(),c->"Mode: "+com.ultimakingdoms.factions.config.FactionConfig.SYNC_MODE.get()+"\n"+(service(c) instanceof FactionServiceImpl impl?impl.diagnosticSummary():"Provider diagnostics unavailable."));
        for(boolean apply:new boolean[]{false,true})task(apply?"migration_apply":"migration_preview",apply?"Import reviewed legacy reputation":"Preview legacy reputation migration",apply,List.of(),c->{var before=service(c).previewLegacyMigration();if(apply&&!before.importable())throw new IllegalArgumentException("Resolve missing sources, mappings or conflicts before importing.");var r=apply?service(c).importLegacyMigration():before;var lines=new ArrayList<String>();lines.add("Source available: "+r.sourceAvailable()+"\nAlready imported: "+r.alreadyImported()+"\nInputs: "+r.inputCount()+"\nUnmapped: "+r.unmapped().size()+"\nReady to import: "+r.importable());r.entries().forEach(e->lines.add(BasicTargets.player(c,e.playerId())+" · "+e.kingdomId().getPath()+" · baseline "+e.baseline()+(e.conflict()?" · conflict with existing score "+e.existingScore():"")));r.unmapped().forEach(e->lines.add(BasicTargets.player(c,e.playerId())+" · "+e.community()+" · "+e.reason()));return lines;});
        task("get","Inspect a player's kingdom standing",false,List.of(pick("player","Player","player"),pick("kingdom","Kingdom","kingdom")),c->service(c).getStanding(c.uuid("player"),c.id("kingdom")).map(v->"Score: "+v.score()+"\nStanding tier: "+v.tierId()).orElse("No record: neutral standing."));
        task("add","Adjust kingdom standing",true,List.of(pick("player","Player","player"),pick("kingdom","Kingdom","kingdom"),number("delta","Standing change (-2000 to 2000)",0)),c->{int delta=c.integer("delta");if(delta< -2000||delta>2000)throw new IllegalArgumentException("Change must be -2000 to 2000.");var r=service(c).apply(new FactionStandingRequest(c.uuid("player"),c.id("kingdom"),delta,new ResourceLocation("ultima_kingdoms","faction_gui"),FactionChangeCause.ADMIN,UUID.randomUUID(),0,Optional.empty(),Optional.of("Reviewed administrative adjustment"),false));return "Applied change: "+r.appliedDelta()+"\nNew score: "+r.standing().score()+"\nStatus: "+words(r.status().name());});
        task("local_effect","Adjust native community standing",true,List.of(pick("player","Player","player"),pick("community","Native community","mca_community"),number("delta","Local change (-100 to 100)",0)),c->{int delta=c.integer("delta");if(delta< -100||delta>100)throw new IllegalArgumentException("Change must be -100 to 100.");return service(c).deliverLocalEffect(c.uuid("player"),McaCommunityRef.parse(c.text("community")).orElseThrow(),delta,UUID.randomUUID(),0,"Reviewed administrative local effect");});
        task("pending_map","Assign an unmapped standing event",true,List.of(pick("event","Pending event","standing_event"),pick("kingdom","Kingdom","kingdom")),c->{if(!(service(c) instanceof FactionServiceImpl impl))throw new IllegalArgumentException("Standing provider unavailable.");var r=impl.resolvePending(c.uuid("event"),c.id("kingdom")).orElseThrow(()->new IllegalArgumentException("Event is no longer awaiting a mapping."));return "Mapping resolved. Applied change: "+r.appliedDelta()+". Status: "+words(r.status().name());});
        add(new Task("administration.integrations","Administration","Check installed integrations","Availability depends on installed versions and server configuration.",true,false,List.of(),c->"",c->{var lines=new ArrayList<String>();for(String id:List.of("mca","mcaquests","mcareputation","mcacrime","townstead","recruits","dotcoinmod","runicskills","runic_gods","runic_races"))lines.add(id+": "+net.minecraftforge.fml.ModList.get().getModContainerById(id).map(m->"installed "+m.getModInfo().getVersion()).orElse("not installed"));lines.add("Civic services: "+com.ultimakingdoms.civic.CivicRuntime.get(c.server()).diagnostic());return lines;}));
    }
    private StandingTasks(){}
}
