package com.ultimakingdoms.interaction;

import com.ultimakingdoms.api.worldcontext.WorldContextApi;
import com.ultimakingdoms.compat.recruits.*;
import com.ultimakingdoms.warfare.*;
import com.ultimakingdoms.warfare.mobilization.*;
import com.ultimakingdoms.warfare.contracts.*;
import com.ultimakingdoms.worldcontext.WorldContextService;
import java.util.*;
import static com.ultimakingdoms.interaction.ActionRegistry.*;

public final class WarfareTasks {
    private static CampaignService campaigns(Context c){return CampaignService.get(c.server());}
    private static WorldContextApi.Provider world(Context c){return WorldContextApi.get(c.server()).orElseThrow(()->new IllegalArgumentException("World exploration is unavailable on this server."));}
    private static WorldContextService author(Context c){if(world(c) instanceof WorldContextService s)return s;throw new IllegalArgumentException("World authoring is unavailable.");}
    private static void task(String id,String title,boolean operator,boolean change,List<Field> fields,Handler handler){add(new Task("warfare."+id,"Warfare",title,"Native faction leadership and current political authorization are checked independently. Review the target and terms; military operations affect the selected settlement.",operator,change,fields,c->campaigns(c).revision()+":"+WarfareRuntime.get(c.server()).revision()+":"+MobilizationSavedData.get(c.server()).revision(),handler));}
    private static void worldTask(String id,String title,boolean operator,boolean change,List<Field> fields,Handler handler){add(new Task("world."+id,"Exploration",title,"Only discovered places and authorized routes are shown. Travel and native objectives remain in the world.",operator,change,fields,c->""+world(c).revision(),handler));}
    public static void init(){
        targets("native_faction",c->c.server().getScoreboard().getPlayerTeams().stream().filter(t->RecruitsMilitary.faction(c.server(),t.getName()).isPresent()).map(t->new Choice(t.getName(),t.getDisplayName().getString())).toList());
        targets("campaign",c->{var out=new ArrayList<Choice>();for(int offset=0;offset<=4096;offset+=64){var page=campaigns(c).campaigns(c.player,offset,64);for(var v:page)out.add(new Choice(v.id().toString(),words(v.goal().name())+" at "+BasicTargets.settlement(c,v.settlement()),words(v.phase().name())+" · "+v.reason(),Map.of("revision",""+campaigns(c).revision())));if(page.size()<64)break;}return out;});
        targets("accord",c->{var out=new ArrayList<Choice>();for(int offset=0;offset<=4096;offset+=64){var page=campaigns(c).accords(c.player,offset,64);for(var v:page)out.add(new Choice(v.id().toString(),words(v.sovereignty().name())+" agreement at "+BasicTargets.settlement(c,v.settlement()),words(v.phase().name())+" · "+v.reason()+" · "+v.signatures().size()+" of 2 signatures\nParties: "+factionName(c,v.first())+" and "+factionName(c,v.second())+"\nNative relation: "+words(v.desired().name())+"\nRecognized kingdom: "+words(new net.minecraft.resources.ResourceLocation(v.recognizedKingdom()).getPath())+"\nExpiry: "+PoliticalTasks.gameTime(v.expires()),Map.of("revision",""+campaigns(c).revision())));if(page.size()<64)break;}return out;});
        targets("deployment",c->{var out=new ArrayList<Choice>();for(int offset=0;offset<=8192;offset+=64){var page=MobilizationEvents.get(c.server()).deployments(c.player,offset,64);for(var v:page){var e=c.player.serverLevel().getEntity(v.unit());out.add(new Choice(v.id().toString(),words(v.doctrine().name())+" deployment · "+(e==null?"recruit (unloaded)":e.getDisplayName().getString()),words(v.phase().name())+" · "+v.detail(),Map.of("revision",""+MobilizationSavedData.get(c.server()).revision())));}if(page.size()<64)break;}return out;});
        targets("site",c->{var out=new ArrayList<Choice>();for(int offset=0;offset<=25000;offset+=32){var page=world(c).sites(c.player,offset,32);for(var v:page)out.add(new Choice(v.id().toString(),words(v.role())+" at "+v.position().toShortString(),v.dimension()+" · "+(v.contested()?"Contested":"Discovered")));if(page.size()<32)break;}return out;});
        targets("route",c->{var out=new ArrayList<Choice>();for(int offset=0;offset<=25000;offset+=32){var page=world(c).routes(c.player,offset,32);for(var v:page){String from=institutionName(c,v.fromInstitution()),to=institutionName(c,v.toInstitution());out.add(new Choice(v.id().toString(),from+" → "+to,"Checkpoint "+(v.nextCheckpoint()+1)+" of "+v.checkpoints().size()+" · "+v.status(),Map.of("revision",""+world(c).revision())));}if(page.size()<32)break;}return out;});
        targets("commodity",c->net.minecraftforge.registries.ForgeRegistries.ITEMS.getEntries().stream().filter(e->e.getValue()!=net.minecraft.world.item.Items.AIR).sorted(Map.Entry.comparingByKey(Comparator.comparing(Object::toString))).map(e->new Choice(e.getKey().location().toString(),words(e.getKey().location().getPath()),e.getKey().location().getNamespace())).toList());
        task("here","Inspect military control here",false,false,List.of(),c->WarfareRuntime.get(c.server()).here(c.player));
        task("inspect","Inspect settlement military control",false,false,List.of(pick("settlement","Settlement","settlement")),c->WarfareRuntime.get(c.server()).view(c.player,c.uuid("settlement")));
        task("map_here","Map the native faction here",true,true,List.of(pick("kingdom","Recognized kingdom","kingdom")),c->WarfareRuntime.get(c.server()).mapHere(c.player,c.id("kingdom")));
        task("bind_here","Bind the current native claim",true,true,List.of(pick("settlement","Settlement","settlement")),c->WarfareRuntime.get(c.server()).bindHere(c.player,c.uuid("settlement")));
        task("retire","Retire a native claim binding",true,true,List.of(pick("settlement","Settlement","settlement")),c->WarfareRuntime.get(c.server()).retire(c.player,c.uuid("settlement"),WarfareRuntime.get(c.server()).revision()));
        task("campaign_overview","Read local campaigns and control agreements",false,false,List.of(pick("settlement","Settlement","settlement")),c->campaigns(c).page(c.player,c.uuid("settlement")));
        task("campaigns","Browse local campaigns",false,false,List.of(pick("campaign","Campaign","campaign")),c->c.choice("campaign").label()+"\n"+c.choice("campaign").detail());
        task("declare","Declare a military campaign",false,true,List.of(pick("goal","Campaign objective",c->enums(CampaignState.Goal.values())),pick("settlement","Target settlement","settlement"),text("reason","Reason and intended outcome")),c->campaigns(c).declare(c.player,UUID.randomUUID(),campaigns(c).revision(),c.uuid("settlement"),CampaignState.Goal.valueOf(c.text("goal").toUpperCase(Locale.ROOT)),c.text("reason")));
        task("retry_campaign","Resume a pending campaign declaration",false,true,List.of(pick("campaign","Campaign","campaign")),c->campaigns(c).applyDeclaration(c.player,c.uuid("campaign")));
        task("withdraw","Withdraw from a campaign",false,true,List.of(pick("campaign","Campaign","campaign")),c->campaigns(c).withdraw(c.player,c.uuid("campaign")));
        task("accord","Propose a settlement control agreement",false,true,List.of(pick("sovereignty","Proposed civic status",c->enums(CampaignState.Sovereignty.values())),pick("settlement","Settlement","settlement"),pick("counterpart","Other native faction","native_faction"),pick("kingdom","Recognized kingdom","kingdom"),text("terms","Agreement terms")),c->campaigns(c).propose(c.player,UUID.randomUUID(),campaigns(c).revision(),c.uuid("settlement"),c.text("counterpart"),CampaignState.Relation.NEUTRAL,CampaignState.Sovereignty.valueOf(c.text("sovereignty").toUpperCase(Locale.ROOT)),c.text("kingdom"),c.text("terms")));
        for(String action:List.of("sign","apply","reject"))task("accord_"+action,words(action)+" a control agreement",false,true,List.of(pick("accord","Control agreement","accord")),c->switch(action){case "sign"->campaigns(c).sign(c.player,c.uuid("accord"),campaigns(c).revision());case "apply"->campaigns(c).applyAccord(c.player,c.uuid("accord"));default->campaigns(c).reject(c.player,c.uuid("accord"),campaigns(c).revision());});
        task("muster","Deploy a recruit temporarily",false,true,List.of(pick("unit","Recruit","native_recruit"),pick("doctrine","Deployment purpose",c->enums(MobilizationDoctrine.values()))),c->MobilizationEvents.get(c.server()).muster(c.player,c.uuid("unit"),MobilizationDoctrine.valueOf(c.text("doctrine").toUpperCase(Locale.ROOT))));
        task("muster_nearby","Deploy nearby recruits temporarily",false,true,List.of(pick("doctrine","Deployment purpose",c->enums(MobilizationDoctrine.values()))),c->MobilizationEvents.get(c.server()).musterNearby(c.player,MobilizationDoctrine.valueOf(c.text("doctrine").toUpperCase(Locale.ROOT))));
        for(String action:List.of("dismiss","recover"))task("deployment_"+action,action.equals("dismiss")?"End a temporary deployment":"Recover a recruit's original orders",false,true,List.of(pick("deployment","Deployment","deployment")),c->action.equals("dismiss")?MobilizationEvents.get(c.server()).dismiss(c.player,c.uuid("deployment")):MobilizationEvents.get(c.server()).recover(c.player,c.uuid("deployment")));
        task("deployments","Inspect an active or retained deployment",false,false,List.of(pick("deployment","Deployment","deployment")),c->c.choice("deployment").label()+"\n"+c.choice("deployment").detail());
        task("contract","Choose civilian recovery work",false,true,List.of(pick("kind","Type of work",c->Arrays.stream(CivilianContractKind.values()).filter(k->!k.scoped()).map(k->new Choice(k.id(),words(k.id()))).toList()),pick("giver","Nearby civilian contact","npc")),c->{var result=CivilianContractService.offer(c.player,BasicTargets.entity(c,"giver"),CivilianContractKind.parse(c.text("kind")));if(!result.success())throw new IllegalArgumentException(PlayerWords.text(result.reason()));return PlayerWords.text(result.reason());});
        worldTask("sites","Browse discovered sites",false,false,List.of(pick("site","Site","site")),c->c.choice("site").label()+"\n"+c.choice("site").detail());
        worldTask("routes","Browse known routes",false,false,List.of(pick("route","Route","route")),c->c.choice("route").label()+"\n"+c.choice("route").detail());
        worldTask("encounters","Read your encounter contributions",false,false,List.of(number("page","Page",1)),c->{int page=c.integer("page");if(page<1||page>1563)throw new IllegalArgumentException("Page must be 1 to 1563.");return world(c).encounters(c.player,(page-1)*16,16).stream().map(v->words(v.encounter().getPath())+" · contribution "+v.contribution()+" · repeat "+v.repeat()).toList();});
        worldTask("route_start","Begin a guided route",false,true,List.of(pick("route","Route","route")),c->worldResult(world(c).beginRoute(c.player,c.uuid("route"))));
        worldTask("resource","Request neutral resource access",false,true,List.of(pick("site","Resource site","site"),pick("commodity","Resource","commodity")),c->worldResult(world(c).requestNeutralResourceAccess(c.player,c.uuid("site"),c.id("commodity"))));
        worldTask("author_site","Create a world site here",true,true,List.of(text("role","Site role (for example camp or resource)")),c->author(c).authorSite(c.player,c.text("role")).map(id->"Site recorded. Players must discover it in person.").orElseThrow(()->new IllegalArgumentException("The site could not be saved.")));
        worldTask("author_route","Create an institution route",true,true,List.of(pick("fromInstitution","Starting institution","institution"),pick("toInstitution","Destination institution","institution")),c->author(c).authorRoute(c.player,c.uuid("fromInstitution"),c.uuid("toInstitution")).map(id->"Route created between the selected institutions.").orElseThrow(()->new IllegalArgumentException("Operational institutions and nearby discovered sites are required.")));
        worldTask("author_resource","Configure neutral resource access",true,true,List.of(pick("site","Resource site","site"),pick("returnSite","Independent return site","site"),pick("commodity","Resource","commodity"),pick("excluded","Excluded commodity","commodity")),c->{if(!author(c).authorNeutralResource(c.player,c.uuid("site"),c.uuid("returnSite"),Set.of(c.id("commodity")),Set.of(c.id("excluded"))))throw new IllegalArgumentException("Both sites must be discovered and the resource site must be outside a settlement.");return "Neutral access policy saved.";});
    }
    private static String factionName(Context c,String id){var team=c.server().getScoreboard().getPlayerTeam(id);return team==null?id:team.getDisplayName().getString();}
    private static String worldResult(WorldContextApi.Action result){if(!result.allowed())throw new IllegalArgumentException(words(result.reason()));return words(result.reason());}
    private static String institutionName(Context c,UUID id){return c.choices("institution").stream().filter(v->v.value().equals(id.toString())).map(Choice::label).findFirst().orElse("Known institution");}
    private WarfareTasks(){}
}
